# Generated by Django 5.0.7 on 2024-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('text', models.TextField()),
                ('photos', models.ManyToManyField(blank=True, related_name='ann_photos', to='landing.photo')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('text', models.TextField()),
                ('photos', models.ManyToManyField(blank=True, related_name='news_photos', to='landing.photo')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('text', models.TextField()),
                ('photos', models.ManyToManyField(blank=True, related_name='report_photos', to='landing.photo')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('text', models.TextField()),
                ('photos', models.ManyToManyField(blank=True, related_name='press_photos', to='landing.photo')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
