# Generated by Django 5.0.7 on 2024-08-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='Отчество')),
                ('describtion', models.TextField(verbose_name='Иноформация')),
                ('profile_image', models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Член совета',
                'verbose_name_plural': 'Члены совета',
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название тэга'),
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название совета')),
                ('chairperson_describtion', models.TextField(verbose_name='Описание председателя')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('chairperson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_chair', to='landing.member', verbose_name='Председатель')),
            ],
            options={
                'verbose_name': 'Региональный совет ректоров',
                'verbose_name_plural': 'Региональные советы ректоров',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)')),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение')),
                ('thumbnail', models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('photos', models.ManyToManyField(blank=True, related_name='news_photos', to='landing.photo', verbose_name='Изображения')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PresidumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_describtion', models.TextField(verbose_name='Описание позиции в президиуме')),
                ('position', models.TextField()),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='landing.member', verbose_name='Член президиума')),
            ],
            options={
                'verbose_name': 'Член президиума',
                'verbose_name_plural': 'Участники президиума',
            },
        ),
        migrations.CreateModel(
            name='Presidum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ограничение на количество')),
                ('members', models.ManyToManyField(null=True, related_name='members', to='landing.presidummember', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Президиум',
                'verbose_name_plural': 'Президиум',
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)')),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение')),
                ('thumbnail', models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст пресс-релиза')),
                ('photos', models.ManyToManyField(blank=True, related_name='press_photos', to='landing.photo', verbose_name='Изображения')),
                ('tags', models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
            },
        ),
    ]
