# Generated by Django 5.0.7 on 2024-08-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_document_member_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='chairperson',
        ),
        migrations.AlterField(
            model_name='member',
            name='describtion',
            field=models.TextField(blank=True, null=True, verbose_name='Иноформация'),
        ),
        migrations.AddField(
            model_name='council',
            name='chairperson',
            field=models.ManyToManyField(blank=True, null=True, related_name='council_chair', to='landing.member', verbose_name='Председатель'),
        ),
    ]
