# Generated by Django 5.0.7 on 2024-07-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_announcement_news_photoreport_press_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
    ]
