# Generated by Django 5.0.7 on 2024-08-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_council_chairperson_alter_member_describtion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='chairperson',
        ),
        migrations.AddField(
            model_name='council',
            name='chairperson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_chair', to='landing.member', verbose_name='Председатель'),
        ),
    ]
