# Generated by Django 5.0.7 on 2024-08-22 23:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_presidummember_member_describtion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='press',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.DeleteModel(
            name='Presidum',
        ),
        migrations.DeleteModel(
            name='Press',
        ),
    ]
