# Generated by Django 5.0.7 on 2024-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_announcement_slug_alter_announcement_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.TextField(default='default'),
        ),
    ]
