# Generated by Django 5.0.7 on 2024-08-22 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_region_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='Слаг', max_length=300, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='landing.region', verbose_name='Регион'),
        ),
    ]
