# Generated by Django 5.0.7 on 2024-08-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_region_slug_alter_university_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=300, verbose_name='Слаг'),
        ),
    ]
