# Generated by Django 5.0.7 on 2024-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='press',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='press',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/'),
        ),
    ]
