# Generated by Django 5.0.7 on 2024-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_region_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Место контента')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Слаг'),
        ),
    ]
