# Generated by Django 5.0.7 on 2024-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_announcement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('decan', models.CharField(max_length=100)),
                ('university_url', models.URLField(blank=True, null=True)),
                ('is_head', models.BooleanField(default=False)),
            ],
        ),
    ]
