# Generated by Django 5.0.7 on 2024-09-01 04:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_editabletext_alter_region_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Tекст', verbose_name='Текст новости'),
        ),
    ]
