# Generated by Django 5.0.7 on 2024-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='default', max_length=250),
        ),
    ]
