# Generated by Django 5.0.7 on 2024-09-01 11:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Tекст', verbose_name='Информация о вузах'),
        ),
    ]
