# Generated by Django 5.0.7 on 2024-09-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_region_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
