# Generated by Django 5.0.7 on 2024-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_alter_member_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Член совета', 'verbose_name_plural': 'Члены совета'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='photoreport',
            options={'verbose_name': 'Фоторепортаж', 'verbose_name_plural': 'Фоторепортажи'},
        ),
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name': 'Пресс-релиз', 'verbose_name_plural': 'Пресс-релизы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='member',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Является членом совета ректоров вузов? '),
        ),
        migrations.AddField(
            model_name='member',
            name='is_member_region',
            field=models.BooleanField(default=False, verbose_name='Является членом регионального совета ректоров вузов? '),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='ann_photos', to='landing.photo', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(verbose_name='Текст анонса'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='member',
            name='decan',
            field=models.CharField(max_length=100, verbose_name='Ректор'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Является главной?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='university',
            field=models.CharField(max_length=100, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='member',
            name='university_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на вуз'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='news_photos', to='landing.photo', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='report_photos', to='landing.photo', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='tags',
            field=models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='text',
            field=models.TextField(verbose_name='Текст фоторепортажа'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='press',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='press',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='press',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='press_photos', to='landing.photo', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='press',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)'),
        ),
        migrations.AlterField(
            model_name='press',
            name='tags',
            field=models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='press',
            name='text',
            field=models.TextField(verbose_name='Текст пресс-релиза'),
        ),
        migrations.AlterField(
            model_name='press',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='press',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг(юрл)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='landing.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='placeholder/default_image.jpg', upload_to='thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='видео файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
