# Generated by Django 5.0.7 on 2024-09-13 02:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='images/', verbose_name='Изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Миниатюра')),
            ],
            options={
                'verbose_name': 'Изображение председателя',
                'verbose_name_plural': 'Изображение председателя',
            },
        ),
        migrations.AlterField(
            model_name='region',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Информация о вузах'),
        ),
    ]
