# Generated by Django 5.0.7 on 2024-08-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('site_name', models.CharField(default='Сайт', max_length=100, verbose_name='Название сайта')),
            ],
            options={
                'verbose_name': 'Региональный совет ректоров',
                'verbose_name_plural': 'Региональные советы ректоров',
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_head',
        ),
        migrations.AddField(
            model_name='member',
            name='site_name',
            field=models.CharField(default='Сайт', max_length=100, verbose_name='Название сайта'),
        ),
    ]
