# Generated by Django 5.0.7 on 2024-08-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_regionsites_remove_member_is_head_member_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
