# Generated by Django 5.0.7 on 2024-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_video_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text',
            field=models.TextField(),
        ),
    ]
